# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ./src --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: NuGetCommand@2
  displayName: 'Restore Nuget dependences'
  inputs:
    command: 'restore'
    restoreSolution: './src'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration) '
  inputs:
    command: 'build'
    projects: './src'
    arguments: '--configuration $(buildConfiguration)'

